FROM nginx

MAINTAINER Sean Grasso

RUN mkdir -p /var/log/app_engine

# Copy and use the customized conf file
COPY nginx.conf /etc/nginx/nginx.conf

# Copy static assets
ADD public/ /etc/nginx/html/public

EXPOSE 8080