FROM nginx

MAINTAINER Sean Grasso

RUN mkdir -p /var/log/app_engine

RUN mkdir -p /usr/share/nginx/www/_ah && \
    echo "healthy" > /usr/share/nginx/www/_ah/health

# Copy and use the customized conf file
COPY nginx.conf /etc/nginx/nginx.conf

# Copy static assets
ADD public/ /etc/nginx/html/public

VOLUME ['/etc/nginx/html/public']

EXPOSE 8080